using System;

namespace Thismaker.Goro
{
    public static partial class IconManager
    {
        /// <summary>
        /// Gets the escape code sequence of the icon for Segoe MDL2 Fonts
        /// </summary>
        /// <returns>A character escape sequence of the icons unicode in Sogoe</returns>
        public static string? ToSegoeCode(this Icon icon)
        {
            return icon switch
            {
                Icon.None => null,
                Icon.Bank => "\uE825",
                Icon.Assessment => "\uE9D9",
                Icon.Article => "\uF000",
                Icon.Book => "\uE82D",
                Icon.Bookmarks => "\uE8A4",
                Icon.Bug => "\uEBE8",
                Icon.Build => "\uE90F",
                Icon.Calendar => "\uE787",
                Icon.CalendarDay => "\uE8BF",
                Icon.CalendarWeek => "\uE8C0",
                Icon.CloseFullscreen => "\uE73F",
                Icon.Commute => "\uF163",
                Icon.ContactInfo => "\uE779",
                Icon.CreditCard => "\uE8C7",
                Icon.Dashboard => "\uF246",
                Icon.Delete => "\uE74D",
                Icon.Done => "\uE930",
                Icon.Eco => "\uEC0A",
                Icon.Eject => "\uF847",
                Icon.Event => "\uEC92",
                Icon.Puzzle => "\uEA86",
                Icon.Face => "\uED53",
                Icon.FavoriteOn => "\uEB52",
                Icon.FavoriteOff => "\uEB51",
                Icon.Feedback => "\uED15",
                Icon.Filter => "\uE71C",
                Icon.Fingerprint => "\uE928",
                Icon.FitScreen => "\uE9A6",
                Icon.Help => "\uE897",
                Icon.History => "\uE81C",
                Icon.Home => "\uE80F",
                Icon.Info => "\uE946",
                Icon.Label => "\uE932",
                Icon.Globe => "\uE774",
                Icon.Lightbulb => "\uEA80",
                Icon.List => "\uE8FD",
                Icon.Lock => "\uE72E",
                Icon.Unlock => "\uE785",
                Icon.Logout => "\uF3B1",
                Icon.Maximize => "\uE922",
                Icon.Minimize => "\uE921",
                Icon.NoteAdd => "\uED0E",
                Icon.OpenInNew => "\uE78B",
                Icon.PanTool => "\uECE9",
                Icon.PowerButton => "\uE7E8",
                Icon.Preview => "\uE8FF",
                Icon.Print => "\uE749",
                Icon.Search => "\uE721",
                Icon.Settings => "\uE713",
                Icon.ShoppingBag => "\uE719",
                Icon.ShoppingCart => "\uE7BF",
                Icon.SpellCheck => "\uF87B",
                Icon.StickyNote => "\uE70B",
                Icon.Swipe => "\uE927",
                Icon.Theaters => "\uE8B2",
                Icon.ThumbUp => "\uE8E1",
                Icon.ThumbDown => "\uE8E0",
                Icon.ThumbsUpDown => "\uE8DF",
                Icon.Today => "\uE8D1",
                Icon.Touch => "\uE815",
                Icon.Translate => "\uF2B7",
                Icon.Trend => "\uEAFC",
                Icon.Update => "\uECC5",
                Icon.UpdateDisabled => "\uE8D8",
                Icon.Eye => "\uE7B3",
                Icon.Work => "\uE821",
                Icon.ZoomIn => "\uE8A3",
                Icon.ZoomOut => "\uE71F",
                Icon.Error => "\uE783",
                Icon.Warning => "\uE7BA",

                //AV
                Icon.Album => "\uE93C",
                Icon.Subtitles => "\uED1E",
                Icon.FastFoward => "\uEB9D",
                Icon.FastRewind => "\uEB9E",
                Icon.Forward30 => "\uED3D",
                Icon.Hearing => "\uF270",
                Icon.Mic => "\uEC71",
                Icon.MicNone => "\uE720",
                Icon.MicOff => "\uF781",
                Icon.Pause => "\uE769",
                Icon.Play => "\uE768",
                Icon.Replay10 => "\uED3C",
                Icon.Shuffle => "\uE8B1",
                Icon.SkipNext => "\uE893",
                Icon.SkipPrevious => "\uE892",
                Icon.Speed => "\uEC4A",
                Icon.Stop => "\uE71A",
                Icon.VideoCall => "\uE8AA",
                Icon.Video => "\uE714",
                Icon.Volume0 => "\uE992",
                Icon.Volume1 => "\uE993",
                Icon.Volume2 => "\uE994",
                Icon.Volume3 => "\uE995",

                //COMM
                Icon.AlternateEmail => "\uE910",
                Icon.Business => "\uE731",
                Icon.Call => "\uF715",
                Icon.CallEnd => "\uE778",
                Icon.CallMerge => "\uEA3C",
                Icon.CallSplit => "\uEA3D",
                Icon.CallReceived => "\uE77E",
                Icon.CallMade => "\uE7F2",
                Icon.Chat => "\uE8BD",
                Icon.Comment => "\uE90A",
                Icon.Contacts => "\uE8D4",
                Icon.Email => "\uE715",
                Icon.Forum => "\uE8F2",
                Icon.Dialpad => "\uE75F",
                Icon.ForwardEmail => "\uE89C",
                Icon.CheckList => "\uE9D5",
                Icon.Location => "\uE81D",
                Icon.NoSim => "\uE876",
                Icon.Phone => "\uE717",
                Icon.PhoneLocked => "\uEC20",
                Icon.QRCode => "\uED14",
                Icon.SentimentSatisfied => "\uE76E",
                Icon.Key => "\uE8D7",
                Icon.WifiCalling => "\uEBD9",
                Icon.Add => "\uE710",
                Icon.AddCircle => "\uECC8",
                Icon.Backspace => "\uEB96",
                Icon.Block => "\uF140",
                Icon.Bolt => "\uE945",
                Icon.Calculator => "\uE8EF",
                Icon.Clear => "\uE894",
                Icon.Copy => "\uE8C8",
                Icon.Cut => "\uE8C6",
                Icon.Paste => "\uE77F",
                Icon.Flag => "\uE7C1",
                Icon.Forward => "\uE72A",
                Icon.Link => "\uE71B",
                Icon.PushPin => "\uE718",
                Icon.Redo => "\uE7A6",
                Icon.Remove => "\uE738",
                Icon.RemoveCircle => "\uECC9",
                Icon.Reply => "\uE97A",
                Icon.Report => "\uE730",
                Icon.Save => "\uE74E",
                Icon.SaveAlt => "\uE78C",
                Icon.SelectAll => "\uE78B",
                Icon.Send => "\uE724",
                Icon.Shield => "\uEA18",
                Icon.Sort => "\uE8CB",
                Icon.Tag => "\uE8EC",
                Icon.TextFormat => "\uE8D3",
                Icon.Undo => "\uE7A7",
                Icon.Clock => "\uE823",
                Icon.AirplaneModeActive => "\uEB4C",
                Icon.AirplaneModeInactive => "\uE709",
                Icon.BatteryAlert => "\uF5F2",
                Icon.BatteryCharging => "\uF607",
                Icon.BatterySaver => "\uEA95",
                Icon.BatteryStd => "\uF5FC",
                Icon.BatteryUnknown => "\uF608",
                Icon.Bluetooth => "\uE702",
                Icon.Devices => "\uE975",
                Icon.Flashlight => "\uE754",
                Icon.ModeLight => "\uE706",
                Icon.ModeNight => "\uE708",
                Icon.Brightness => "\uE793",
                Icon.NetworkCell => "\uE870",
                Icon.NetworkWifi => "\uE701",
                Icon.Radar => "\uEB44",
                Icon.Restart => "\uF83E",
                Icon.RotationLock => "\uE755",
                Icon.SDCard => "\uE7F1",
                Icon.Storage => "\uEDA2",
                Icon.USB => "\uE88E",


                //Editor
                Icon.Attach => "\uE723",
                Icon.BarChart => "\uE9D2",
                Icon.DragHandle => "\uE76F",
                Icon.FormatAlignLeft => "\uE8E4",
                Icon.FormatAlignRight => "\uE8E2",
                Icon.FormatAlignCenter => "\uE8E3",
                Icon.FormatBold => "\uE8DD",
                Icon.FormatColorText => "\uE8D3",
                Icon.FormatItalic=> "\uE8DB",
                Icon.FormatBulletedList => "\uE8FD",
                Icon.FormatQuote => "\uE9B1",
                Icon.FormatStrikethrough => "\uEDE0",
                Icon.FormatUnderline => "\uE8DC",
                Icon.FormatSize => "\uE8E9",
                Icon.Highlight => "\uE7E6",
                Icon.PieChart => "\uEB05",

                //File
                Icon.Cloud => "\uE753",
                Icon.NewFolder => "\uE8F4",
                Icon.Download => "\uE896",
                Icon.Folder => "\uED41",
                Icon.FolderOpen => "\uED43",
                Icon.GridView => "\uF0E2",
                Icon.Upload => "\uE898",

                //Hardware
                Icon.Desktop => "\uE7F4",
                Icon.Laptop => "\uE7F8",
                Icon.Earbuds => "\uF4C0",
                Icon.Headphones => "\uE7F6",
                Icon.Headset => "\uE95B",
                Icon.Keyboard => "\uE92E",
                Icon.KeyboardReturn => "\uE751",
                Icon.KeyboardTab => "\uE7FD",
                Icon.Mouse => "\uE962",
                Icon.Scanner => "\uE8FE",
                Icon.Speaker => "\uE7F5",
                Icon.Gamepad => "\uE7FC",
                Icon.Reading => "\uE736",
                Icon.Camera => "\uE722",
                Icon.CircleRing => "\uEA3A",
                Icon.CircleFill => "\uEA3B",
                Icon.ColorPalette => "\uE790",
                Icon.Crop => "\uE7A8",
                Icon.Edit => "\uE70F",
                Icon.MusicNote => "\uEC4F",
                Icon.Nature => "\uE8BE",
                Icon.Photo => "\uEB9F",
                Icon.Rotate => "\uE7AD",
                Icon.Slideshow => "\uE786",
                Icon.Timer => "\uE916",
                Icon.View360 => "\uF131",
                Icon.Car => "\uE804",
                Icon.Ferry => "\uE7E3",
                Icon.Walk => "\uE805",
                Icon.Bus => "\uE806",
                Icon.Train => "\uE7C0",
                Icon.Layers => "\uE81E",
                Icon.Food => "\uED56",
                Icon.Fire => "\uECAD",


                Icon.Apps => "\uED35",
                Icon.ArrowUp => "\uF0AD",
                Icon.ArrowDown => "\uF0AE",
                Icon.ArrowLeft => "\uF0B0",
                Icon.ArrowRight => "\uF0AF",
                Icon.ChevronUp => "\uE70E",
                Icon.ChevronDown => "\uE70D",
                Icon.ChevronLeft => "\uE76B",
                Icon.ChevronRight => "\uE76C",
                Icon.Cancel => "\uE711",
                Icon.Check => "\uE73E",
                Icon.Fullscreen => "\uE740",
                Icon.FullscreenExit => "\uE73F",
                Icon.Menu => "\uE700",
                Icon.More => "\uE712",
                Icon.Refresh => "\uE72C",

                Icon.Construction => "\uEC7A",
                Icon.Group => "\uE902",
                Icon.Notifications => "\uEA8F",
                Icon.NotificationsOff => "\uE7ED",
                Icon.People => "\uE716",
                Icon.Person => "\uE77B",
                Icon.PersonAdd => "\uE8FA",
                Icon.World => "\uE909",
                Icon.School => "\uE7BE",
                Icon.Share => "\uE72D",
                Icon.Checkbox => "\uE73A",
                Icon.CheckboxBlank => "\uE739",
                Icon.CheckboxIntermediate => "\uE73C",
                Icon.StarOn => "\uE735",
                Icon.StarHalf => "\uF0E7",
                Icon.StarOff => "\uE734",
                Icon.ToggleOff => "\uF19E",
                Icon.ToggleOn => "\uF19F",
                Icon.Sync => "\uE895",
                Icon.SyncError => "\uEA6A",
                Icon.Buildings => "\uEC06",
                _ => throw new InvalidOperationException("Unknown icon")
            };
        }

    }
}
